### ISSUE TITLE
Screenshots of Web UI needed

### ISSUE THREAD

**Issue by jchristi** [PerfCake/PerfRepo#43]
I am interested in this tool but don't want to spend the time to install it just to see what it looks like. Please add some screenshots to the README file so we can get a quick look. Thanks!

**Comment by Holmistr** [comment]
Hi @jchristi , thank you for your interest! I'm a little busy right now, but I will try to get back to you as soon as possible, let's say in next 2 days. I hope you'll still be interested :)

**Comment by jchristi** [comment]
Sounds good, thanks

**Comment by Holmistr** [comment]
@jchristi Oh, man, I completely forgot about you, sorry, abou that!! I was on a vacation and then I forgot. Putting it on my wall right in front of my eyes, I'll get back to you. Sorry

**Comment by jchristi** [comment]
Cool, thx

**Comment by Holmistr** [comment]
@jchristi I will not promise anything anymore, I'm ashamed. I was planning to create a complete Docker image with example data, however, then master branch broke after rebasing to Wildfly and since then, I'm currently stuck with other work. I can currently only point you to the Docker images with no data, see: https://github.com/PerfCake/Docker

**Comment by jchristi** [comment]
@Holmistr okay, thanks for following up. If I have the time I'll spin up a docker host and check it out but I may not have the time either.
