### ISSUE TITLE
Public reports

### ISSUE THREAD

**Issue by vjuranek** [PerfCake/PerfRepo#99]
Currently only user with an account can see a report. Sometimes it's useful to show the results also to wilder audience. It would be nice to have an option to publish a report which can be access by anybody without need to log in.

**Comment by mgencur** [comment]
I think there is a way for some kinds of reports to be accessible without login.
See for example: http://perfrepo.mw.lab.eng.bos.redhat.com:8080/reports/tablecomparisonreport/4782
In order to access it without login you need to use camel case in the type of the report: http://perfrepo.mw.lab.eng.bos.redhat.com:8080/reports/tableComparisonReport/4782
For simple metric report it's not even required to use camel case, the URL is same.
But the report needs to have the right permissions: AccessLevel: Public, AccessType: READ (this can be changed in the configuration of the report when you're logged in)

**Comment by vjuranek** [comment]
thanks a lot @mgencur ! Changing the behaviour (and especially security!) based on upper/lower letters in URL seems to me, let's say ... little bit unfortunate decision, but this is different issue. Thanks for letting me know!

**Comment by mgencur** [comment]
No problem. I think it's not changing security, it's just a way to tell PerfRepo to skip the login screen. But the report already has to have "PUBLIC" permissions. If you access a private report using camel case, you'll get an error.

**Comment by vjuranek** [comment]
it's not about skipping login screen, but about user being authenticated or not. And if this can be changed just by making URL camel case, this is at least very confusing sooner or later leading to leaking something (i.e. after quick check how perfrepo behaves, what probably most uses do to find out, I concluded that public report means that it can be seen by anybody with account, but not by unauthenticated user). 

 If I make report public, it can either mean that everybody who has account can see it or really everybody (without need to authenticate). If original intention was to make the report public, I don't understand why camel case URL should matter.
